azl397985856/leetcode

- README.en.md
- README.md
> Add English README

- problems/20.validParentheses.md
修改了：
所属项目： valid parenthesis 
1 python 和 javascript的代码说明
2 增加了python code 左侧的空格
3 说明了本次联系的支持语言
> 第0020题目增加python代码支持

- problems/3.longestSubstringWithoutRepeatingCharacters.md
> Added problem link for problem 3

- problems/20.validParentheses.md
add python code to ValidParentheses
> update ValidParentheses with python code

- daily/2019-06-03.md
- daily/README.md
Add 2019-06-03.md
Modify README.md
> 更新每日一题-20190603

- daily/2019-06-10.md
- daily/README.md
每日一题 617. Merge Two Binary Trees
> 617.Merge Two Binary Trees

- problems/121.best-time-to-buy-and-sell-stock.md
- problems/122.best-time-to-buy-and-sell-stock-ii.md
仿照现有的格式, 
增加了python实现, 
请review下, 看看有没有问题.
计划在两周内给每道题目添加python实现.
> add python implementation to problem 121 and problem 122

- README.en.md
> correct some grammar mistakes

- problems/26.remove-duplicates-from-sorted-array.md
problem No.26 remove duplicates from sorted array add python code
> feat: 26.remove-duplicates-from-sorted-array add Python3 implementation

- problems/88.merge-sorted-array.md
Fix solution on problem 88, fixs #62
>  Fix solution on problem 88, fixs #62

- problems/104.maximum-depth-of-binary-tree.md
add python3 implementation for problem 104
> feat: 104.maximum-depth-of-binary-tree add Python3 implementation

- problems/121.best-time-to-buy-and-sell-stock.md
> feat: 121.best-time-to-buy-and-sell-stock update Python3 implementation

- problems/125.valid-palindrome.md
add python implementation for problem No.125
> feat: 125.valid-palindrome add Python3 implementation

- problems/129.sum-root-to-leaf-numbers.md
add python3 implementation for problem No.129
> feat: 129.sum-root-to-leaf-numbers add Python3 implementation

- problems/155.min-stack.md
add python3 implementation for problem No.155
> feat: 155.min-stack add Python3 implementation

- problems/172.factorial-trailing-zeroes.md
add python3 implementation for problem No.172
> feat: 172.factorial-trailing-zeroes add Python3 implementation

- problems/167.two-sum-ii-input-array-is-sorted.md
add python3 implementation for problem No.167
> feat: 167.two-sum-ii-input-array-is-sorted add Python3 implementation

- problems/169.majority-element.md
add python3 implementation for problem No.169
> feat: 169.majority-element add Python3 implementation

- problems/190.reverse-bits.md
add python implementation for problem No.190
> feat: 190.reverse-bits add Python3 implementation

- problems/191.number-of-1-bits.md
add python implementation for problem No.191
> feat: 191.number-of-1-bits add Python3 implementation

- problems/198.house-robber.md
> feat: add some notes in 198.house-robber.md

- problems/198.house-robber.md
add python implementation for problem No.198
> feat: 198.house-robber add Python3 implementation

- problems/203.remove-linked-list-elements.md
add python implementation for problem No.203
> feat: 203.remove-linked-list-elements add Python3 implementation

- problems/206.reverse-linked-list.md
add python implementation for problem No.206
> feat: 206.reverse-linked-list add Python3 implementation

- problems/219.contains-duplicate-ii.md
add python implementation for problem No.219
> feat: 219.contains-duplicate-ii add Python3 implementation

- problems/226.invert-binary-tree.md
add python implementation for problem No.226
> feat: 226.invert-binary-tree add Python3 implementation

- problems/232.implement-queue-using-stacks.md
add python implementation for problem No.232
> feat: 232.implement-queue-using-stacks add Python3 implementation

- problems/283.move-zeroes.md
add python implementation for problem No.283
> feat: 283.move-zeroes add Python3 implementation

- problems/342.power-of-four.md
add python implementation for problem No.342
> feat: 342.power-of-four add Python3 implementation

- problems/263.ugly-number.md
add python implementation for problem No.263
> feat: 263.ugly-number add Python3 implementation

- problems/349.intersection-of-two-arrays.md
add python implementation for problem No.349
> feat: 349.intersection-of-two-arrays add Python3 implementation

- problems/560.subarray-sum-equals-k.md
add python implementation for problem No.560
> feat: 560.subarray-sum-equals-k add Python3 implementation

- problems/46.permutations.md
add new Python implementation for problem No.46
> feat: 46.permutations update Python3 implementation

- problems/575.distribute-candies.md
add python implementation for problem No.575
> feat: 575.distribute-candies update Python3 implementation

- problems/53.maximum-sum-subarray-cn.md
change the divide & conquer solution space complexity.
> fix: #53 空间复杂度修改

- problems/42.trapping-rain-water.md
> feat: #42 python3 Code added

- problems/73.set-matrix-zeroes.md
> Add python solution

- problems/445.add-two-numbers-ii.md
> feat: #445 Add python3 solution

- problems/23.merge-k-sorted-lists.md
Add python3 solution to 23.merge-k-sorted-lists
> feat: #23 Add python3 solution

- problems/236.lowest-common-ancestor-of-a-binary-tree.md
and also delete duplicate information
> feat: #236 add python 🐍 solution

- problems/200.number-of-islands.md
> Update 200: add python code

- problems/15.3-sum.md
a trick to improve performence
> perf: a little tricky $15.3-sum

- problems/283.move-zeroes.md
- problems/98.validate-binary-search-tree.md
> 283.move-zeroes 错别字修正

- problems/25.reverse-nodes-in-k-groups-cn.md
- problems/32.longest-valid-parentheses.md
- problems/4.median-of-two-sorted-array.md
> feat: add js solution for #25 #32

- problems/15.3-sum.md
since left < right, and left > i, no need to compare i === left and i === right
> chore: delete no need compare

- problems/79.word-search.md
修改
if (board == null || word == null) return false;
if (word.length() == 0) return true;
if (board.length == 0) return false;
> fix: $79 boundary check

- problems/240.search-a-2-d-matrix-ii.md
if (!matrix || matrix.length === 0) return false;
> fix: return type $240

- problems/1371.find-the-longest-substring-containing-vowels-in-even-counts.md
change left value and add semicolon;
> fix: $1371

- problems/88.merge-sorted-array.md
> feat(ml): $88.merge-sorted-array.md

- problems/200.number-of-islands.md
> feat(ml): $200.number-of-islands.md

- problems/219.contains-duplicate-ii.md
> feat(ml):$219.contains-duplicate-ii.md

- problems/172.factorial-trailing-zeroes.md
> feat(ml):$172.factorial-trailing-zeroes.md

- problems/78.subsets.md
> feat(ml): $78.subsets.md

- problems/21.merge-two-sorted-lists.md
> Merge two sorted-lists add solution

- problems/1.two-sum.md
> 更新时间复杂度为O(n)的其他语言实现

- problems/1.two-sum.en.md
> Two Sum--Add O(n) solution code

- problems/20.valid-parentheses.md
> 20.有效括号-增加其他语言版本Solution

- problems/125.valid-palindrome.md
> 验证回文串——增加Java版本Solution

- problems/66.plus-one.md
> 加一——增加Java版Solution

- problems/122.best-time-to-buy-and-sell-stock-ii.md
> 买卖股票的最佳时机II -增加Python贪心策略Solution

- problems/26.remove-duplicates-from-sorted-array.md
>  删除排序数组中的重复项——增加Java版本双指针解法

- problems/203.remove-linked-list-elements.md
> 移除链表元素——增加迭代解法

- problems/190.reverse-bits.md
> 颠倒二进制位——增加java版log(n)解法

- problems/191.number-of-1-bits.md
> 位 1 的个数——增加Java版O(logn)解法

- problems/198.house-robber.md
> 打家劫舍——增加Java版动态规划优化空间O(1)解法

- problems/2817.minimum-absolute-difference-between-elements-with-constraint.md
> feat: add problem $2817

- daily/2019-06-04.md
- daily/2019-07-25.md
This pull request fixes some typos in daily problems of 2019.
I kindly request the repository maintainers to review and merge it.
Thanks! :heart:
> fix typos in daily problems of 2019:
